<!--
============================================================================
Asignatura: Desarrollo de Aplicaciones Web (Código: 0423807T)
Facilitador: M.Sc. Ing. Gabriel Alexis Ramírez Sánchez
email: gramirezs@unet.edu.ve
Período Académico: Septiembre, 2026
San Cristóbal, Estado Táchira, Venezuela
============================================================================
-->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="FluentAssertions" Version="6.12.2" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\backend\Core.Application\Core.Application.csproj" />
    <ProjectReference Include="..\..\src\backend\Core.Domain\Core.Domain.csproj" />
  </ItemGroup>

</Project>
